from pathlib import Path
import re

html = Path('index.html').read_text()
js = Path('main.js').read_text()

replacements = [
("Youssef Mohamed - IT Infrastructure & Security Engineer specializing in network infrastructure, cybersecurity, and IoT security systems.",
 "Youssef Mohamed - Junior System & Network Administrator specializing in Windows Server administration, network infrastructure, and hands-on IT support."),
("IT infrastructure, network security, cybersecurity, Cisco, firewall, VLAN, OSPF, IoT security, ESP32, security engineer, NTI",
 "Junior System & Network Administrator, Windows Server, Active Directory, DNS, DHCP, Group Policy, Cisco, VLAN, OSPF, IT infrastructure, technical support, NTI"),
("Youssef Mohamed - IT Infrastructure & Security Engineer",
 "Youssef Mohamed - Junior System & Network Administrator"),
("Building secure network infrastructure with focus on cybersecurity best practices and IoT security solutions.",
 "Building reliable IT infrastructure through Windows Server administration, networking, and practical troubleshooting."),
("<title>Youssef Mohamed | IT Infrastructure & Security Engineer</title>",
 "<title>Youssef Mohamed | Junior System & Network Administrator</title>"),
("<p>Loading Secure Portfolio...</p>", "<p>Loading Portfolio...</p>"),
("                Security focused <strong>IT Infrastructure Engineer</strong> with a <strong>strong technical triad in Networking</strong>, <strong>System Administration</strong>, and <strong>Cybersecurity</strong>.\n              <br>\n                I am a Business Information Systems student <strong>(Expected Graduation: 2026)</strong> with extensive <strong>technical training from NTI</strong>. I specialize in designing secure network topologies <strong>(CCNA)</strong>, managing Windows Server environments <strong>(MCSA)</strong>, and implementing robust security controls <strong>(CompTIA Security+)</strong>. My goal is to build reliable, high-performance IT infrastructures that are hardened against modern cyber threats.",
 "                Junior <strong>System & Network Administrator</strong> with hands-on experience in <strong>Windows Server administration</strong>, <strong>network infrastructure</strong>, and <strong>technical support</strong>.\n              <br>\n                I am a Business Information Systems student <strong>(Expected Graduation: 2026)</strong> with practical lab experience in <strong>AD DS, DNS, DHCP, Group Policy, WSUS, WDS, Hyper-V</strong>, and enterprise networking using <strong>Cisco Packet Tracer</strong>. My goal is to join an entry-level role in <strong>System Administration</strong>, <strong>Network Administration</strong>, or <strong>IT Infrastructure</strong>."),
("                  <span class=\"stat-label\">Certifications</span>", "                  <span class=\"stat-label\">Training Programs</span>"),
("                  <span class=\"stat-number\" data-target=\"2\">0</span>", "                  <span class=\"stat-number\" data-target=\"3\">0</span>"),
("                  <span class=\"stat-label\">Major Projects</span>", "                  <span class=\"stat-label\">Featured Projects</span>"),
("                    alt=\"Youssef Mohamed - IT Infrastructure & Security Engineer\"",
 "                    alt=\"Youssef Mohamed - Junior System & Network Administrator\""),
("                  <span>NTI Certified</span>", "                  <span>Windows Server & Networking Track</span>"),
("              Building Secure Digital Foundations", "Building Reliable IT Foundations"),
("                As an <strong>IT Infrastructure & Security Engineer</strong>, I\n                focus on designing and implementing secure network architectures\n                that protect critical infrastructure while ensuring optimal\n                performance and reliability.",
 "                As a <strong>Junior System & Network Administrator</strong>, I focus on building and supporting reliable Windows Server and network environments through hands-on labs, structured troubleshooting, and practical infrastructure implementation."),
("                    <h3>Network Infrastructure</h3>\n                    <p>Designing and configuring secure network topologies</p>",
 "                    <h3>System Administration</h3>\n                    <p>Managing AD DS, DNS, DHCP, Group Policy, WSUS, and Hyper-V</p>"),
("                    <h3>Security Fundamentals</h3>\n                    <p>Implementing cybersecurity best practices</p>",
 "                    <h3>Enterprise Networking</h3>\n                    <p>Configuring VLANs, routing, ACLs, NAT/PAT, and secure access</p>"),
("                    <h4>Hardware & Technical Support</h4>\n                    <p>Computer & Laptop Repair Technician</p>",
 "                    <h4>Computer & Laptop Repair Technician</h4>\n                    <p>Smart Computer Systems | Technical support, maintenance, and troubleshooting</p>"),
("              Detailed Overview", "Detailed Professional Overview"),
("                  <h3>IT Infrastructure & Security Engineer</h3>", "                  <h3>Junior System & Network Administrator</h3>"),
("                    Motivated IT Infrastructure & Security Engineer with a solid\n                    foundation in network infrastructure, cybersecurity basics,\n                    and technical troubleshooting. Business Information Systems\n                    (BIS) student (Expected Graduation: 2026) with intensive\n                    training from the National Telecommunication Institute\n                    (NTI).",
 "                    Junior System & Network Administrator with hands-on experience in Windows Server administration, network infrastructure, and technical support. Business Information Systems student with practical training through NTI programs and self-driven lab environments focused on real administrative tasks and troubleshooting."),
("                          Business Information Systems (BIS) student at EGI\n                          Academy – Higher Institute for Specific Studies\n                          (Expected Graduation: 2026) | GPA: 3.4 / 4.0",
 "                          Bachelor of Management Information Systems (BIS) at EGI Academy, expected October 2026, with a GPA of 3.4 / 4.0."),
("                          Intensive training from the National Telecommunication\n                          Institute (NTI) in cybersecurity and network\n                          infrastructure",
 "                          Completed multiple NTI and ITIDA training programs in networking, network security, and cybersecurity fundamentals."),
("                          Designing secure networks, configuring\n                          routers/switches, and implementing IoT-based safety\n                          systems",
 "                          Windows Server administration, enterprise networking, infrastructure troubleshooting, and applied IoT safety integration."),
("                  <span class=\"language-level\">Professional Working</span>", "                  <span class=\"language-level\">Professional Working Proficiency</span>"),
("                  <span class=\"learning-tag\">SOC Operations</span>\n                  <span class=\"learning-tag\">Advanced Network Security</span>\n                  <span class=\"learning-tag\">IoT Security Protocols</span>\n                  <span class=\"learning-tag\">Cyber Defense Strategies</span>\n                  <span class=\"learning-tag\">Security+ Certification Prep</span>",
 "                  <span class=\"learning-tag\">Windows Server Administration</span>\n                  <span class=\"learning-tag\">Active Directory Services</span>\n                  <span class=\"learning-tag\">Enterprise Networking</span>\n                  <span class=\"learning-tag\">Infrastructure Troubleshooting</span>\n                  <span class=\"learning-tag\">Security Fundamentals</span>"),
("            <button class=\"filter-btn\" data-filter=\"security\">Security</button>\n            <button class=\"filter-btn\" data-filter=\"iot\">IoT</button>\n            <button class=\"filter-btn\" data-filter=\"tools\">Tools</button>",
 "            <button class=\"filter-btn\" data-filter=\"system\">System</button>\n            <button class=\"filter-btn\" data-filter=\"security\">Security</button>\n            <button class=\"filter-btn\" data-filter=\"tools\">Tools</button>"),
("                  <span>Cybersecurity Fundamentals</span>\n                  <span class=\"progress-value\">90%</span>",
 "                  <span>Windows Server Administration</span>\n                  <span class=\"progress-value\">92%</span>"),
("                  <div class=\"progress-fill\" data-width=\"90\"></div>", "                  <div class=\"progress-fill\" data-width=\"92\"></div>"),
("                  <span>IoT & Hardware</span>\n                  <span class=\"progress-value\">85%</span>",
 "                  <span>Technical Support & Troubleshooting</span>\n                  <span class=\"progress-value\">90%</span>"),
("                  <div class=\"progress-fill\" data-width=\"85\"></div>", "                  <div class=\"progress-fill\" data-width=\"90\"></div>"),
("            <p>Interested in more technical projects?</p>", "            <p>Project videos and deeper case studies will be added soon.</p>"),
("              Request Detailed Case Studies", "Contact Me for Details"),
("              All certifications are verified and up-to-date", "Training and certifications listed here are based on my latest CV"),
("              Professional Communication", "Let\'s Connect"),
("                <p class=\"contact-note\">Encrypted email preferred</p>", "                <p class=\"contact-note\">Best for job opportunities and professional communication</p>"),
("                <p class=\"contact-note\">Signal/WhatsApp available</p>", "                <p class=\"contact-note\">Calls and WhatsApp available</p>"),
("                <p class=\"contact-note\">Available for remote security audits</p>", "                <p class=\"contact-note\">Open to internships and entry-level IT roles</p>"),
("                <h3>Secure Message</h3>", "                <h3>Send a Message</h3>"),
("                  <span>Messages are encrypted and secure</span>", "                  <span>I usually reply through email or WhatsApp</span>"),
("                  <span class=\"btn-text\">Send Secure Message</span>", "                  <span class=\"btn-text\">Send Message</span>"),
("            <p class=\"footer-tagline\">Securing Digital Infrastructure</p>", "            <p class=\"footer-tagline\">Windows Server | Networking | IT Infrastructure</p>"),
("            <h4>Technical Updates</h4>", "            <h4>Stay Connected</h4>"),
("            <p>Get the latest cybersecurity and infrastructure insights</p>", "            <p>Leave your email and I can connect with you later.</p>"),
("            NTI Certified IT Infrastructure & Security Engineer", "Junior System & Network Administrator"),
]
for old,new in replacements:
    if old not in html:
        print('MISSING HTML:', old[:80])
    html = html.replace(old,new)

# Strong cleanup for footer resources
html = html.replace('<li><a href="#" id="privacyLink">Privacy Policy</a></li>\n                <li><a href="#" id="termsLink">Terms</a></li>', '<li><a href="CV.pdf" download="Youssef_Mohamed_CV.pdf">Download CV</a></li>\n                <li><a href="https://www.linkedin.com/in/youssef-mohamed-sec/" target="_blank" rel="noopener noreferrer">LinkedIn</a></li>')

# JS: replace header comment and typing texts, portfolio data object and project link rendering
js = js.replace('// Portfolio Application - IT Infrastructure & Security Engineer','// Portfolio Application - Junior System & Network Administrator')
js = re.sub(r'this\.typingTexts = \[[\s\S]*?\];', 'this.typingTexts = [\n      "Junior System & Network Administrator",\n      "Windows Server & Active Directory",\n      "Network Infrastructure & Technical Support",\n    ];', js)

new_data = '''this.portfolioData = {
      skills: [
        {
          id: 1,
          icon: "fas fa-server",
          title: "System Administration",
          tags: [
            "Windows Server",
            "Active Directory Domain Services (AD DS)",
            "DNS",
            "DHCP",
            "Group Policy",
            "OU Design",
            "RSAT",
            "File Server",
            "DFS",
            "WSUS",
            "WDS",
            "Hyper-V",
            "Backup & Recovery",
          ],
          category: "system",
        },
        {
          id: 2,
          icon: "fas fa-network-wired",
          title: "Networking",
          tags: [
            "TCP/IP",
            "IPv4/IPv6",
            "Subnetting",
            "VLANs",
            "Inter-VLAN Routing",
            "OSPF",
            "ACLs",
            "NAT",
            "PAT",
            "SSH",
            "Wireless Basics",
            "Router & Switch Configuration",
          ],
          category: "network",
        },
        {
          id: 3,
          icon: "fas fa-shield-alt",
          title: "Infrastructure & Security Fundamentals",
          tags: [
            "Firewall Fundamentals",
            "Zone-Based Policy Firewall (ZPF)",
            "Port Security",
            "Secure Management Access",
            "Patch Management",
            "Access Control",
            "Monitoring & Logging",
            "Infrastructure Troubleshooting",
          ],
          category: "security",
        },
        {
          id: 4,
          icon: "fas fa-tools",
          title: "Technical Tools",
          tags: [
            "Cisco Packet Tracer",
            "VMware Workstation",
            "Wireshark",
            "PowerShell",
            "ADUC",
            "GPMC",
            "DNS Manager",
            "DHCP Console",
            "Server Manager",
          ],
          category: "tools",
        },
        {
          id: 5,
          icon: "fas fa-microchip",
          title: "IoT & Applied Integration",
          tags: [
            "ESP32",
            "Environmental Sensors",
            "Dashboard Monitoring",
            "Mobile App Control",
            "YOLO-based Video Analysis",
            "Real-time Hazard Detection",
          ],
          category: "tools",
        },
      ],

      projects: [
        {
          id: 1,
          title: "Windows Server Administration Lab",
          description: `Built and administered a Windows Server lab environment from scratch including AD DS, DNS, DHCP, OU design, users and groups, Group Policy, File Server, DFS, WSUS, WDS, Hyper-V, and backup and recovery.`,
          technologies: [
            "Windows Server",
            "AD DS",
            "DNS",
            "DHCP",
            "Group Policy",
            "WSUS",
            "WDS",
            "Hyper-V",
            "PowerShell",
          ],
          icon: "fas fa-server",
          year: "2026",
          link: "#contact",
          linkLabel: "Ask for Lab Details",
          details:
            "Troubleshot real issues involving DNS resolution, GPO application, WSUS behavior, remote management, multi-NIC domain controller misconfiguration, RSAT setup, DFS, and FSMO role operations.",
        },
        {
          id: 2,
          title: "Enterprise Network Infrastructure Project",
          description: `Designed and implemented a secure enterprise network simulation connecting headquarters and branches using Cisco Packet Tracer. Configured structured subnetting, VLAN segmentation, Inter-VLAN Routing, centralized DHCP, SSH management, multi-area OSPF, Static NAT, PAT, ACLs, wireless connectivity, and Zone-Based Policy Firewall.`,
          technologies: [
            "Cisco Packet Tracer",
            "VLANs",
            "Inter-VLAN Routing",
            "OSPF",
            "DHCP",
            "ACLs",
            "NAT/PAT",
            "ZPF",
            "SSH",
          ],
          icon: "fas fa-network-wired",
          year: "2026",
          link: "project1.mp4",
          linkLabel: "View Demo Video",
          details:
            "Applied enterprise networking practices including segmentation, access control, traffic filtering, and secure management to reflect a realistic infrastructure deployment.",
        },
        {
          id: 3,
          title: "Intelligent Hybrid AI Safety System",
          description: `Co-developed an intelligent safety system integrating computer vision, environmental sensors, ESP32, dashboard monitoring, and mobile application control for real-time hazard detection and response.`,
          technologies: [
            "ESP32",
            "Computer Vision",
            "Environmental Sensors",
            "Dashboard Monitoring",
            "Mobile App Control",
            "Hazard Detection",
          ],
          icon: "fas fa-temperature-high",
          year: "2026",
          link: "#contact",
          linkLabel: "Project Media Coming Soon",
          details:
            "Combined YOLO-based video analysis with gas, flame, and temperature sensors to detect fire, smoke, gas leakage, and abnormal events. Achieved 2nd place in the Geniuses Forum competition.",
        },
      ],

      certifications: [
        {
          id: 1,
          name: "CCNAv7 Program",
          issuer: "National Telecommunication Institute (NTI)",
          icon: "fas fa-network-wired",
          year: "2026",
          credential: "Networking Training Program",
          verified: false,
        },
        {
          id: 2,
          name: "Windows Server Administration (MCSA Track)",
          issuer: "Udemy",
          icon: "fab fa-microsoft",
          year: "2026",
          credential: "Windows Server Administration",
          verified: false,
        },
        {
          id: 3,
          name: "CompTIA Security+ (SY0-601)",
          issuer: "Netriders",
          icon: "fas fa-shield-alt",
          year: "2026",
          credential: "Security+ Preparation Track",
          verified: false,
        },
        {
          id: 4,
          name: "Network Infrastructure Summer Training Program",
          issuer: "NTI / ITIDA",
          icon: "fas fa-server",
          year: "2025",
          credential: "Infrastructure Training",
          verified: false,
        },
        {
          id: 5,
          name: "Network Security Program",
          issuer: "National Telecommunication Institute (NTI)",
          icon: "fas fa-user-shield",
          year: "2025",
          credential: "Network Security Training",
          verified: false,
        },
        {
          id: 6,
          name: "Cybersecurity Superhero Academy",
          issuer: "NTI / EG-CERT / NTRA",
          icon: "fas fa-certificate",
          year: "2025",
          credential: "Cybersecurity Training",
          verified: false,
        },
      ],
    };'''
js = re.sub(r'this\.portfolioData = \{[\s\S]*?\n    \};', new_data, js, count=1)

js = js.replace('<span>View Details</span>', '<span>${project.linkLabel || "View Details"}</span>')

Path('index.html').write_text(html)
Path('main.js').write_text(js)
print('[OK] updated portfolio files')
